version: '3.7'
services:
  web:
    build: ./docker/web
    container_name: transactions_web
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    networks:
      - backend
  mysql:
    image: mysql:8
    container_name: transactions_mysql
    restart: always
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=transactions
      - MYSQL_USER=transactions
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_PASSWORD=p@ssw0rd
    ports:
      - 33060:3306
    networks:
      - backend

networks:
  backend: